/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <sys/time.h>
#include "miniop.h"

#define MILLION 1000000L

/* Variables para controlar el tiempo. */
struct timeval start, end;
unsigned long accum;

void print_header();
void print_options();
void record_init_time();
void record_end_time();
void handle_addition();
void handle_substraction();
void handle_product();
void handle_division();
void handle_dectobin();
void handle_bintohexa();
CLIENT * get_clnt(char *host);
void destroy_clnt(CLIENT * clnt);

int main (int argc, char *argv[]){

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	print_header();

	char *host;
	host = argv[1];
	
	/* Creo el handler para cominicarme con el server */
	CLIENT * clnt = get_clnt(host);
	
	if(clnt == NULL){
		exit(1);
	}

	int op;
	char retry = 'x';
	
	while(retry!='n'){
		fflush(stdin);
		print_options();
		scanf("%i",&op);
		
		switch(op){
			case 1:
				handle_dectobin(clnt);
				break;
			case 2:
				handle_bintohexa(clnt);
				break;
			case 3:
				handle_addition(clnt);
				break;
			case 4:
				handle_substraction(clnt);
				break;
			case 5:
				handle_product(clnt);
				break;
			case 6:
				handle_division(clnt);
				break;
			case 7:
				retry='n';
				break;
			default:
				break;
		}
		
		int i=0;
		while(retry!='y' && retry!='n'){
			printf("\nDesea realizar otra operación? (y/n): ");
			fflush(stdin);
			scanf(" %c",&retry);
		}

		if(retry=='n'){
			printf("Goodbye! \n");
		}else if( retry=='y' ){
			retry='x';
		}
		
	}

	destroy_clnt(clnt);

	exit (0);

}

void print_header(){
	printf("******************************************************************************\n");
	printf("****************************** MINI OPERACIONES ******************************\n");
	printf("******************************************************************************\n\n");
}

void print_options(){
	printf("\n¿Qué desea hacer?\n");
	printf("	1. Convertir un número de decimal a binario.\n");
	printf("	2. Convertir un número binario a hexadecimal.\n");
	printf("	3. Sumar números (hasta 4 operandos).\n");
	printf("	4. Restar números (hasta 4 operandos).\n");
	printf("	5. Multiplicar dos números.\n");
	printf("	6. Dividir dos números.\n");
	printf("	7. Salir.\n\n");
	printf("Ingrese una opcion: ");
}

void record_init_time(){

	/* Registro tiempo inicial */
	if(gettimeofday(&start,NULL)<0){
		perror("Error en start");
	}
	
}

void record_end_time(){

	/* Registro tiempo final */
	if(gettimeofday(&end,NULL)<0){
		perror("Error en end");
	}

	/* Obtengo el tiempo transcurrido en microsegundos */
	if(end.tv_sec==start.tv_sec){
		accum = ( end.tv_sec - start.tv_sec ) * MILLION + ( end.tv_usec - start.tv_usec ); 
	}else{
		accum = ( end.tv_sec - start.tv_sec )* MILLION + (MILLION - start.tv_usec) + end.tv_usec ; 
	}

}

void handle_dectobin(CLIENT * clnt){

	
	number_conv  *result_5;
	long  dectobin_1_arg;
	
	printf("Ingrese un numero positivo en decimal: ");
	scanf("%ld",&dectobin_1_arg);

	record_init_time();

	result_5 = dectobin_1(&dectobin_1_arg, clnt);
	
	record_end_time();
	
	if (result_5 == (number_conv *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("Resultado en binario: %s\n", result_5->num);
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);
	
}

void handle_bintohexa(CLIENT * clnt){

	number_conv  *result_6;
	long  bintohexa_1_arg;
	
	printf("Ingrese un numero en binario: ");
	scanf("%ld",&bintohexa_1_arg);

	record_init_time();

	result_6 = bintohexa_1(&bintohexa_1_arg, clnt);

	record_end_time();
	
	if (result_6 == (number_conv *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("Resultado en hexadecimal: %s\n", result_6->num);
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);
}

void handle_addition(CLIENT * clnt){

	float  *result_1;
	aritmetic_req  add_1_arg;
	int cant_op = 0;
	int i;
	float aux[4];
	
	printf("Ingrese el número de operandos: ");
	scanf("%i",&cant_op);
	
	while( (cant_op<2) || (cant_op>4) ){
		printf("Ingrese un número entre 2 y 4: ");
		scanf("%i",&cant_op);
	}
	
	add_1_arg.cant_op = cant_op;
	
	for(i=0;i<cant_op;i++){
		printf("Ingrese operando: ");
		scanf("%f",&aux[i]);
	}
	
	for(i=0;i<cant_op;i++){
		add_1_arg.arr[i] = aux[i];
	}


	record_init_time();

	result_1 = add_1(&add_1_arg, clnt);

	record_end_time();
	
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("Resultado de la suma: %.2f\n", (*result_1));
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);

}

void handle_substraction(CLIENT * clnt){

	float  *result_2;
	aritmetic_req  sub_1_arg;
	int cant_op = 0;
	int i;
	float aux[4];
	
	printf("Ingrese el número de operandos: ");
	scanf("%i",&cant_op);
	
	while( (cant_op<2) || (cant_op>4) ){
		printf("Ingrese un número entre 2 y 4: ");
		scanf("%i",&cant_op);
	}
	
	sub_1_arg.cant_op = cant_op;
	
	for(i=0;i<cant_op;i++){
		printf("Ingrese operando: ");
		scanf("%f",&aux[i]);
	}
	
	for(i=0;i<cant_op;i++){
		sub_1_arg.arr[i] = aux[i];
	}

	record_init_time();

	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	record_end_time();
	
	printf("Resultado de la resta: %.2f\n", (*result_2));
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);

}

void handle_product(CLIENT * clnt){

	float  *result_3;
	aritmetic_req  mul_1_arg;
	int cant_op = 2;
	int i;
	float aux[2];
	
	for(i=0;i<cant_op;i++){
		printf("Ingrese operando: ");
		scanf("%f",&aux[i]);
	}
	
	mul_1_arg.cant_op = cant_op;
	
	for(i=0;i<cant_op;i++){
		mul_1_arg.arr[i] = aux[i];
	}

	record_init_time();

	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	record_end_time();
	
	printf("Resultado del producto: %.2f\n", (*result_3));
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);
	
}

void handle_division(CLIENT * clnt){

	float  *result_4;
	aritmetic_req  div_1_arg;
	int cant_op = 2;
	int i;
	float aux[2];
	
	printf("Ingrese dividendo: ");
	scanf("%f",&aux[0]);
	
	printf("Ingrese divisor: ");
	scanf("%f",&aux[1]);

	while(aux[1]==0){
		printf("El divisor no puede ser cero.\n");
		printf("Ingrese divisor: ");
		scanf("%f",&aux[1]);
	}
	
	div_1_arg.cant_op = cant_op;
	
	for(i=0;i<cant_op;i++){
		div_1_arg.arr[i] = aux[i];
	}

	record_init_time();

	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	record_end_time();
	
	printf("Resultado de la división: %.2f\n", (*result_4));
	printf("Tiempo de ejecución: %lu microsegundos.\n",accum);
	
}


CLIENT * get_clnt(char *host){

	CLIENT *clnt;

	clnt = clnt_create (host, MINIOPERACIONES, MINIOPERACIONESVERS, "tcp");
	
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		return NULL;
	}
	
	return clnt;
	
}

void destroy_clnt(CLIENT * clnt){

	clnt_destroy(clnt);
}
