/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"
#include <time.h>
#include <unistd.h>
#include <sys/wait.h>

#define COMMAND "./tarea"
#define BILLION 1000000000L

int * calc_time_1_svc(void *argp, struct svc_req *rqstp){

	static int  result;

	/*
	 * insert server code here
	 */
	 
	struct timespec start, end;
	unsigned long accum;
	 
	 pid_t pid;

	/* Registro tiempo inicial */
	if(clock_gettime(CLOCK_REALTIME, &start)<0){
		perror("Error en start");
	}
	
	if( (pid = fork() ) == 0 ){
	
		/* Estoy en el hijo */
		if( execl(COMMAND,NULL) < 0 ){
			perror("Error en execl");
			exit(-1);
		}
		
	}

	/* Registro tiempo final */
	if(clock_gettime(CLOCK_REALTIME, &end)<0){
		perror("Error en end");
	}

	/* Obtengo el tiempo transcurrido en nanosegundos */
	if(end.tv_sec==start.tv_sec){
		accum = ( end.tv_sec - start.tv_sec ) * BILLION + ( end.tv_nsec - start.tv_nsec ); 
	}else{
		accum = ( end.tv_sec - start.tv_sec )* BILLION + (BILLION - start.tv_nsec) + end.tv_nsec ; 
	}
	
	result = accum/1000;
	
	wait(NULL);

	return &result;
	
}

int * calc_time_system_1_svc(void *argp, struct svc_req *rqstp){

	static int  result;

	/*
	 * insert server code here
	 */
	 
	struct timespec start, end;
	unsigned long accum;
	 
	 /* Registro tiempo inicial */
	if(clock_gettime(CLOCK_REALTIME, &start)<0){
		perror("Error en start");
	}

	system(COMMAND);

	/* Registro tiempo final */
	if(clock_gettime(CLOCK_REALTIME, &end)<0){
		perror("Error en end");
	}
	
	/* Obtengo el tiempo transcurrido en nanosegundos */
	if(end.tv_sec==start.tv_sec){
		accum = ( end.tv_sec - start.tv_sec ) * BILLION + ( end.tv_nsec - start.tv_nsec ); 
	}else{
		accum = ( end.tv_sec - start.tv_sec )* BILLION + (BILLION - start.tv_nsec) + end.tv_nsec ; 
	}
	 
	result = accum/1000;

	return &result;

}
