/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"

int * calc_time_1_svc(void *argp, struct svc_req *rqstp){
	static int  result;

	/*
	 * insert server code here
	 */
	 printf("calc_time_1_svc\n");

	return &result;
}

int * calc_time_system_1_svc(void *argp, struct svc_req *rqstp){
	static int  result;

	/*
	 * insert server code here
	 */
	 printf("calc_time_system_1_svc\n");
	 result = 10;

	return &result;
}
